"""Bibliography for the write-up. Keys are cited in build.py with cite("key");
numbers are assigned in order of first citation."""

REFS = {
    # Brief and team documents
    "brief": "Yuva Yodha Energy Tech Hackathon, “Grid Reliability: Renewable Intermittency — making clean power dependable, neighbourhood by neighbourhood”, problem statement, 2026.",
    "research": "LEO team, “Grid Reliability and Renewable Intermittency: Architecting Dependable Local Power Networks Through Distributed Flexibility” (research plan compiling the sources cited below), October 2026.",
    "proposal": "LEO team, “LEO — Local Energy Orchestrator: Working Proposal”, Section 2 “Design Philosophy: What We Adopted, and From Where”, September 2026.",
    "arch": "LEO team, “LEO — System Architecture v3.0” and “LEO — Build Specification v1.0”, October 2026.",
    # Policy and regulation
    "ceew": "M. Sikdar, A. Woodward, D. Aggarwal, Y. Sun, “How Can India Create a Demand Flexibility Market? A Roadmap for a Flexible Power System”, CEEW and Centre for Net Zero, June 2026. https://www.ceew.in/sites/default/files/ceew-how-can-india-create-a-demand-flexibility-market-web-ready.pdf",
    "merc": "Maharashtra Electricity Regulatory Commission (Demand Flexibility and Demand Side Management, Measurement and Verification) Regulations, 2024. https://www.legitquest.com/act/maharashtra-electricity-regulatory-commission-demand-flexibility-and-demand-side-managementmeasurement-and-verification-regulations-2024/1079F",
    "merc_draft": "Draft MERC (Demand Flexibility and Demand Side Management) Regulations. https://avantiscdnprodstorage.blob.core.windows.net/legalupdatedocs/34874/DRAFTM~1.PDF",
    "saur_merc": "Saur Energy, “MERC New Regulation Sets 7% Flexible Demand Target For Next Five Years”. https://www.saurenergy.com/solar-energy-news/merc-new-regulation-sets-7-flexible-demand-target-for-next-five-years",
    "mercom_kerc": "Mercom India, “Karnataka Notifies Framework for Demand Flexibility and Demand-Side Management”, 24 March 2026. https://mercomindia.com/karnataka-notifies-framework-for-demand-flexibility-and-demand-side-management",
    "nie_kerc": "The New Indian Express, “KERC issues orders for demand side management, flexible targets”, 24 March 2026. https://www.newindianexpress.com/states/karnataka/2026/Mar/24/kerc-issues-orders-for-demand-side-management-flexibile-targets",
    "sq_kerc": "SolarQuarter, “KERC Introduces Demand Flexibility and DSM Regulations 2026 to Improve Power Efficiency in Karnataka”, 24 March 2026.",
    "aggregator": "LawGratis, “Legal Status of Demand Aggregators in Electricity Markets”. https://lawgratis.com/blog-detail/legal-status-of-demand-aggregators-in-electricity-markets",
    "ea2003": "The Electricity Act, 2003 (consolidated, CERC), Sections 12–14.",
    "consumer_rules": "Ministry of Power, Electricity (Rights of Consumers) Rules, 2020, as amended 2023 (time-of-day tariffs: peak ≥1.10× for domestic, ≥1.20× for C&I; solar hours ≥20% below normal).",
    "sq_tod": "SolarQuarter, “BESCOM Seeks KERC Approval To Levy ₹1.65 Per Unit Additional Surcharge On Open Access Consumers In Karnataka” (FY 2025-26 tariff order: 30% peak surcharge, 25% off-peak rebate), October 2025. https://solarquarter.com/2025/10/14/",
    "jmk_tod": "Concept paper on ToD tariff for solar and non-solar hours (Uttarakhand), January 2026. https://jmkresearch.com/wp-content/uploads/2026/01/Uttarakhand-proposes-solar-based-time-of-day-tariff-to-boost-renewables-and-manage-peak-demand.pdf",
    "kerc_pmsg": "Mercom India, “KERC Proposes Tariff of ₹2.93/kWh for PM Surya Ghar Projects Above 3 kW”. https://www.mercomindia.com/",
    "dpdp": "Digital Personal Data Protection Act, 2023 (India).",
    "trai": "Telecom Regulatory Authority of India, Telecom Commercial Communications Customer Preference Regulations, 2018 (DLT).",
    # DISCOM and grid evidence
    "hindu_dt": "The Hindu, “BESCOM loses 16,749 transformers in seven months”. https://www.thehindu.com/news/cities/bangalore/bescom-loses-16749-transformers-in-seven-months/article71463090.ece",
    "dt_failure": "“Transformer Failure Rates and Reliability Analysis” (ResearchGate). https://www.researchgate.net/publication/390464330",
    "dt_premature": "“Premature failure of distribution transformers — a case study” (SciSpace). https://scispace.com/pdf/premature-failure-of-distribution-transformers-a-case-study-8cp7gm0uks.pdf",
    "dt_overload": "“Distribution Transformer Overload: Signs, Risks & Failure Timeline”. https://www.jszonma.com/blog/what-happens-when-a-distribution-transformer-is-overloaded-signs-risks-and-failure-timeline",
    "dt_repair": "International Copper Association India, “Report on Repair for Performance Improvement of Distribution Transformers for MPPKVVCL”, October 2019.",
    "hindu_loss": "The Hindu, “BESCOM records single-digit distribution losses two years in a row”. https://www.thehindu.com/news/cities/bangalore/bescom-records-single-digit-distribution-losses-two-years-in-a-row-bengaluru/article69461506.ece",
    "ember": "Ember, “The age of storage: Batteries primed for India's power markets”, Chapter 2. https://ember-energy.org/latest-insights/the-age-of-storage-batteries-primed-for-indias-power-markets/",
    "ranjith_iex": "Ranjith's Energy Digest, “IEX Power Analysis 2023–25”. https://www.ranjithenergydigest.com/insights/power/IEX-Power-Analysis-23-25",
    "energymap": "India Energy Atlas, IEX DAM and RTM analytics. https://www.energymap.in/iex-market",
    "ijert_iex": "IJERT, “Impact of Renewable Energy Production on Thermal Generation and Electricity Pricing Dynamics in India: A Comprehensive Market Analysis using IEX and Grid India Data 2014–2024”.",
    "iex": "Indian Energy Exchange, Day-Ahead and Real-Time Market rules and market data. https://www.iexindia.com/market-data/day-ahead-market/market-snapshot",
    "bses_sla": "BSES Delhi, Amended Service Level Agreement, Section 6 Cl. 14, AMISP RFP (derived from the national standard bidding document).",
    "rec_ladakh": "REC Power Development and Consultancy Ltd, clarifications to the Ladakh RfP for smart metering.",
    "prayas_sm": "S. Kulkarni, A. Apte, K. Sehgal, “Smart Metering in India: A Work in Progress”, Prayas (Energy Group), May 2025.",
    "rdss": "Energetica India, “India Installs Over 5.28 Crore Smart Meters Under RDSS” (Ministry of Power data), February 2026.",
    "ies": "India Energy Stack (Ministry of Power; REC nodal agency), IES Accelerator specifications and pilot status.",
    "esmi": "Prayas (Energy Group), Electricity Supply Monitoring Initiative (ESMI), watchyourpower.org; data on Harvard Dataverse.",
    "emarc": "Prayas (Energy Group), Energy Monitoring and Analysis of Residential Consumption (eMARC), Pune.",
    "nline": "nLine / PowerWatch outage and voltage monitoring deployment, Accra, Ghana.",
    "nfms": "Ministry of Power / REC, National Feeder Monitoring System.",
    "sldc": "Karnataka State Load Despatch Centre, real-time system data portal.",
    "cea_interop": "Central Electricity Authority, report on interoperability of smart metering under RDSS.",
    # DR evidence
    "tata_ddl": "Tata Power-DDL behavioural demand response programme: 2,041 enrolled domestic consumers, 56% average participation per event (75% peak), 21% average reduction vs baseline; ₹250/event for >10% reduction plus ₹200 sign-up, other tiers ₹50/₹100; 16, 12 and 16 events in FY22–FY24, ≤2 h, 3–4 per month April–September (compiled in team research notes).",
    "bypl": "BSES Yamuna Power Ltd and AEEE, automated demand response pilot: 48 households; 1–5 kW spot reduction for a 30-customer cluster (0.03–0.16 kW per connected customer); ₹1 per kWh saved (compiled in team research notes).",
    "imperial_tata": "Imperial College London and Tata Power, randomised trial of smart-switch demand response with residential customers in Mumbai and New Delhi.",
    "caiso_dr": "CAISO, “Demand Response Advanced Measurement Methodology”, updated February 2022.",
    "ac_share": "Household air-conditioner ownership in India (~8% nationally, concentrated in higher-income urban homes) (compiled in team research notes).",
    "smart_devices": "Indian retail pricing for Wi-Fi IR blasters (₹799–999) and smart AC remote + 16 A smart plug bundles (~₹2,090) (compiled in team research notes).",
    # Industry and academic precedents (proposal Section 2)
    "huang": "K. Huang, L. Cheng, Y. Zhou, F. Shi, Y. Xi, Y. Zhuang, N. Qi, “Real-Time Peer-to-Peer Energy Trading for Multi-Microgrids: Improved Double Auction Mechanism and Prediction-Free Online Trading Approach”, arXiv:2510.02985, 2025.",
    "schneider": "Schneider Electric, EcoStruxure ADMS and EcoStruxure DERMS — technical feature and applications overview.",
    "sonnen": "sonnen GmbH, sonnenCommunity — shared virtual battery pool model. https://sonnen.com.au/sonnencommunity/",
    "brooklyn": "“Energiewende in Brooklyn”, Bulletin (SEV/VSE): retrospective on Brooklyn Microgrid / LO3 Energy, with commentary from E. Mengelkamp and Y. Dvorkin. https://www.bulletin.ch/de/news-detail/energiewende-in-brooklyn.html",
    "comillas": "Comillas Pontifical University, doctoral thesis, “Comparative analysis of local energy trading market models: centralized server vs. distributed ledger (blockchain) implementations”. http://hdl.handle.net/11531/95590",
    "powerledger": "Power Ledger, India Smart Grid Forum and UPPCL, “First P2P Solar Power Trading in South Asia”, December 2020 (12-participant pilot, initial phase mock trading only).",
    "prayas_bhiwandi": "Prayas (Energy Group), “Review of the Distribution Franchisee Model Implemented by MSEDCL in the Bhiwandi Circle”, June 2009.",
    "indinfra_df": "Indian Infrastructure, “Limited Success: Revisiting the Distribution Franchise Model”, November 2016.",
    "csep_df": "Centre for Social and Economic Progress, “Rethinking Franchisee Efficacy in India's Power Sector: A Critique of Input-Based Distribution Models”, working paper.",
    "li_linucb": "L. Li, W. Chu, J. Langford, R. Schapire, “A contextual-bandit approach to personalized news article recommendation”, WWW 2010.",
    "grid2op": "RTE France, Grid2Op — reinforcement-learning environment for transmission-grid operation (considered and rejected).",
    # Batteries
    "frontiers_2l": "“Lithium-ion battery second life: pathways, challenges and outlook”, Frontiers in Chemistry, 2024. https://www.frontiersin.org/journals/chemistry/articles/10.3389/fchem.2024.1358417/full",
    "mdpi_thermal": "“A Review of Thermal Safety and Management of Second-Life Batteries”, MDPI Batteries 12(3):99.",
    "mdpi_degr": "“Degradation Prediction and Cost Optimization of Second-Life Battery”, MDPI Energies 16(17):6200.",
    "wri_2l": "WRI India, “Second Charge: Unlocking Second-Life Potential of EV Batteries”. https://wri-india.org/perspectives/second-charge-unlocking-second-life-potential-ev-batteries",
    "pvmag_2l": "pv magazine India, “Falling Li-ion battery prices mirror solar PV trends: is there a role for second-life batteries before recycling?”, 23 May 2025.",
    "ieee_c5791": "IEEE Std C57.91, Guide for Loading Mineral-Oil-Immersed Transformers and Step-Voltage Regulators (thermal model and ageing acceleration factor).",
    # Opex evidence
    "dlt": "Ojiva AI, “DLT Registration for Bulk SMS in India” (one-time ₹5,900). https://www.ojiva.ai/blogs/dlt-registration-bulk-sms-india/",
    "sms_cost": "Exotel, “TRAI Regulations — Sending SMS in India”; MessageBot, “Bulk SMS Pricing in India” (≈₹0.12 + ₹0.025 DLT scrubbing per SMS).",
    "wages": "Labour Law Help, “Karnataka Minimum Wages Revised From 22 May 2026” (skilled electrician, Zone 1: ₹32,144.82/month). https://labourlawhelp.com/karnataka-minimum-wages/",
    # Standards and protocols
    "ipmvp": "Efficiency Valuation Organization, International Performance Measurement and Verification Protocol (IPMVP), Option C (whole facility).",
    "dlms": "IS 15959; IEC 62056 (DLMS/COSEM); IS 16444 (smart meters).",
    "lorawan": "LoRa Alliance, LoRaWAN Regional Parameters (IN865–867); ChirpStack network server.",
    "mqtt": "OASIS, MQTT Version 5.0 / 3.1.1.",
    "sunspec": "SunSpec Alliance, SunSpec Modbus information models for inverters and storage.",
    "iec62116": "IEC 62116 (anti-islanding test procedure for utility-interconnected PV inverters); IEEE 1547-2018 (interconnection of distributed energy resources).",
    "cim": "IEC 61968 / IEC 61970 Common Information Model.",
    "openadr": "OpenADR Alliance, OpenADR 2.0 / 3.0; IEEE 2030.5.",
    "beckn": "Beckn protocol specifications; W3C Decentralized Identifiers v1.0; W3C Verifiable Credentials Data Model.",
    "openems": "OpenEMS, open-source energy management system.",
    # Tools and data
    "pandapower": "L. Thurner et al., “pandapower — an open-source Python tool for convenient modeling, analysis, and optimization of electric power systems”, IEEE Trans. Power Systems, 2018.",
    "pvlib": "W. F. Holmgren, C. W. Hansen, M. A. Mikofski, “pvlib python: a python package for modeling solar energy systems”, JOSS, 2018.",
    "lightgbm": "G. Ke et al., “LightGBM: A Highly Efficient Gradient Boosting Decision Tree”, NeurIPS 2017.",
    "cvxpy": "S. Diamond, S. Boyd, “CVXPY”, JMLR 2016; B. Stellato et al., “OSQP”, Math. Prog. Comp., 2020.",
    "openmeteo": "Open-Meteo historical weather and forecast APIs. https://open-meteo.com/",
    "osm": "OpenStreetMap contributors; G. Boeing, “OSMnx”, 2017.",
    "deckgl": "deck.gl, WebGL-powered visualization framework (OpenJS Foundation).",
    "nsrdb": "National Renewable Energy Laboratory, National Solar Radiation Database (NSRDB).",
}
