"""Generate 10_data_model.mmd (Mermaid erDiagram) from contracts/ddl.sql.

Shows primary keys, foreign keys and a few defining columns per table, so the
diagram stays readable and never drifts from the schema."""
import re
from pathlib import Path

ddl = (Path(__file__).resolve().parents[2] / "contracts" / "ddl.sql").read_text()
import sys
CORE = None if "--full" in sys.argv else {"run","household","bus","sensor","sensor_reading","meter_interval","forecast","network_result","plan","dispatch","event","mode_transition","dr_event","dr_offer","ledger","period_revenue","recommendation","premise_meter","consent","battery_block"}
SKIP = {"household_truth"}  # hidden simulator truth, never visible to LEO
KEEP_EXTRA = 3 if CORE is None else 1

tables = {}
for m in re.finditer(r"CREATE TABLE(?: IF NOT EXISTS)?\s+(\w+)\s*\((.*?)\n\);", ddl, re.S):
    name, body = m.group(1), m.group(2)
    if name in SKIP or (CORE is not None and name not in CORE):
        continue
    cols, fks, pk = [], [], set()
    for line in body.split("\n"):
        line = line.split("--")[0].strip().rstrip(",")
        if not line:
            continue
        pkm = re.match(r"PRIMARY KEY\s*\(([^)]*)\)", line)
        if pkm:
            pk |= {c.strip() for c in pkm.group(1).split(",")}
            continue
        if re.match(r"(UNIQUE|CHECK|CONSTRAINT|FOREIGN KEY)", line):
            continue
        cm = re.match(r"(\w+)\s+([A-Za-z_]+)", line)
        if not cm:
            continue
        col, typ = cm.group(1), cm.group(2).lower()
        if "PRIMARY KEY" in line:
            pk.add(col)
        ref = re.search(r"REFERENCES\s+(\w+)", line)
        if ref:
            fks.append((col, ref.group(1)))
        cols.append((col, typ))
    tables[name] = (cols, pk, dict(fks))

lines = ["%% Generated by gen_er.py from contracts/ddl.sql - do not edit by hand.", "erDiagram"]
for name, (cols, pk, fks) in tables.items():
    for col, ref in fks.items():
        if ref in tables and ref != name:
            lines.append(f'    {ref} ||--o{{ {name} : "{col}"')
for name, (cols, pk, fks) in tables.items():
    lines.append(f"    {name} {{")
    extra = 0
    for col, typ in cols:
        key = "PK" if col in pk else ("FK" if col in fks else "")
        if not key:
            if extra >= KEEP_EXTRA:
                continue
            extra += 1
        lines.append(f"        {typ} {col}{(' ' + key) if key else ''}")
    lines.append("    }")
(Path(__file__).parent / ("10_data_model_full.mmd" if CORE is None else "10_data_model.mmd")).write_text("\n".join(lines) + "\n")
print(f"{len(tables)} tables")
